In [55]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [56]:
df = pd.read_csv('dataset.csv')

In [57]:
df.describe()

Disease  Symptom_1  Symptom_2 Symptom_3    Symptom_4  Symptom_5  \
count       4920       4920       4920      4920         4572       3714   
unique        41         34         48        54           50         38   
top     Impetigo   vomiting   vomiting   fatigue   high_fever   headache   
freq         120        822        870       726          378        348   

       Symptom_6        Symptom_7        Symptom_8           Symptom_9  \
count       2934             2268             1944                1692   
unique        32               26               21                  22   
top       nausea   abdominal_pain   abdominal_pain   yellowing_of_eyes   
freq         390              264              276                 228   

                Symptom_10     Symptom_11 Symptom_12         Symptom_13  \
count                 1512           1194        744                504   
unique                  21             18         11                  8   
top      yellowing_of_eyes   irritability    malaise   stomach_bleeding   
freq                   198            120        126                 72   

         Symptom_14   Symptom_15        Symptom_16    Symptom_17  
count           306          240               192            72  
unique            4            3                 3             1  
top      chest_pain   chest_pain   blood_in_sputum   muscle_pain  
freq             96          144                72            72

In [58]:
df.Disease.value_counts()

Impetigo                                   120
Cervical spondylosis                       120
GERD                                       120
Hepatitis C                                120
Fungal infection                           120
Gastroenteritis                            120
(vertigo) Paroymsal  Positional Vertigo    120
Peptic ulcer diseae                        120
Hepatitis B                                120
Chicken pox                                120
Allergy                                    120
Hepatitis D                                120
Hypothyroidism                             120
Hepatitis E                                120
hepatitis A                                120
Migraine                                   120
Arthritis                                  120
Jaundice                                   120
Hypertension                               120
Paralysis (brain hemorrhage)               120
AIDS                                       120
Tuberculosis 

In [59]:
sum(df.duplicated())

4616

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Disease     4920 non-null   object
 1   Symptom_1   4920 non-null   object
 2   Symptom_2   4920 non-null   object
 3   Symptom_3   4920 non-null   object
 4   Symptom_4   4572 non-null   object
 5   Symptom_5   3714 non-null   object
 6   Symptom_6   2934 non-null   object
 7   Symptom_7   2268 non-null   object
 8   Symptom_8   1944 non-null   object
 9   Symptom_9   1692 non-null   object
 10  Symptom_10  1512 non-null   object
 11  Symptom_11  1194 non-null   object
 12  Symptom_12  744 non-null    object
 13  Symptom_13  504 non-null    object
 14  Symptom_14  306 non-null    object
 15  Symptom_15  240 non-null    object
 16  Symptom_16  192 non-null    object
 17  Symptom_17  72 non-null     object
dtypes: object(18)
memory usage: 692.0+ KB


In [61]:
df1 = df.drop_duplicates()

In [62]:
df1.Disease.value_counts()

Chicken pox                                10
Dengue                                     10
Migraine                                   10
Hepatitis D                                10
Typhoid                                     9
Hepatitis E                                 9
Common Cold                                 9
hepatitis A                                 9
Pneumonia                                   9
Hepatitis B                                 9
Hypoglycemia                                9
Diabetes                                    9
Tuberculosis                                9
Jaundice                                    9
Hyperthyroidism                             9
Alcoholic hepatitis                         8
Chronic cholestasis                         8
Varicose veins                              8
Malaria                                     8
Hypothyroidism                              8
Psoriasis                                   7
(vertigo) Paroymsal  Positional Ve

In [63]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 304 entries, 0 to 407
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Disease     304 non-null    object
 1   Symptom_1   304 non-null    object
 2   Symptom_2   304 non-null    object
 3   Symptom_3   304 non-null    object
 4   Symptom_4   272 non-null    object
 5   Symptom_5   234 non-null    object
 6   Symptom_6   186 non-null    object
 7   Symptom_7   158 non-null    object
 8   Symptom_8   140 non-null    object
 9   Symptom_9   120 non-null    object
 10  Symptom_10  110 non-null    object
 11  Symptom_11  68 non-null     object
 12  Symptom_12  47 non-null     object
 13  Symptom_13  30 non-null     object
 14  Symptom_14  19 non-null     object
 15  Symptom_15  18 non-null     object
 16  Symptom_16  10 non-null     object
 17  Symptom_17  1 non-null      object
dtypes: object(18)
memory usage: 45.1+ KB


In [64]:
def make_cols(df, col_names):
    for name in col_names:
        if not name:
            continue
        df[name] = 0
    return df

In [65]:
def data_in_cols(col_name, df):
    for val in df[col_name].unique():
        df.loc[df[col_name] == val, val] = 1
    return df


In [66]:
for col in df1.columns[:18]:
    df1 = make_cols(df1, df1[col].unique())

E:\eng_progam\Anaconda\program\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


In [67]:
# df2.loc[df['Disease'] == df['Disease'].unique()[0], df['Disease'].unique()[0]]

In [68]:
for col in df1.columns[:18]:
    df1 = data_in_cols(col, df1)


E:\eng_progam\Anaconda\program\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [69]:
df1.drop(columns=df.columns, inplace=True)

E:\eng_progam\Anaconda\program\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [87]:
df1 = df1.sample(frac=1).reset_index(drop=True)
df1.shape

(304, 173)

In [88]:
y = df1[df.Disease.unique()]
y.shape

(304, 41)

In [89]:
X = df1.iloc[:, df.Disease.nunique():]
X.shape

(304, 132)

In [95]:
tree_clf = DecisionTreeClassifier(max_depth=6)

In [91]:
tree_clf.fit(X, y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [112]:
from sklearn.tree import export_graphviz

In [114]:
export_graphviz(
    tree_clf,
    out_file=('mlu2.dot'),
    feature_names=X_train.columns,
    class_names=y_train.columns,
    rounded=True,
    filled=True
)

In [92]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [166]:
tree_clf = DecisionTreeClassifier(max_depth=40)
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=40, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [167]:
from sklearn.metrics import f1_score

predictions = tree_clf.predict(X_test)
f1 = f1_score(y_test, predictions, average='micro')
f1

0.7017543859649122

In [168]:
predictions.sum(axis=1)

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1], dtype=int64)

In [178]:
from sklearn.svm import SVC

In [186]:
from sklearn.multiclass import OneVsRestClassifier
lsvc = OneVsRestClassifier(SVC(C=1, kernel="linear", decision_function_shape='ovo'))

In [187]:
lsvc.fit(X_train, y_train)

OneVsRestClassifier(estimator=SVC(C=1, break_ties=False, cache_size=200,
                                  class_weight=None, coef0=0.0,
                                  decision_function_shape='ovo', degree=3,
                                  gamma='scale', kernel='linear', max_iter=-1,
                                  probability=False, random_state=None,
                                  shrinking=True, tol=0.001, verbose=False),
                    n_jobs=None)

In [188]:
predictionss = lsvc.predict(X_test)
f1s = f1_score(y_test, predictionss, average='micro')
f1s

1.0

In [191]:
np.array(y_test).sum(axis=1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [192]:
predictionss.sum(axis=1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [193]:
predictions.sum(axis=1)

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1], dtype=int64)